   name: Deploy to Server

   on:
     push:
       branches:
         - main  # 或者你使用的分支

   jobs:
     deploy:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       - name: Set up SSH
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
           chmod 600 ~/.ssh/deploy_key
           ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

       - name: Deploy to server
         env:
           DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
           USERNAME: ${{ secrets.USERNAME }}
           HOST: ${{ secrets.HOST }}
           PORT: ${{ secrets.PORT }}
         run: |
           rsync -avz --delete --exclude='.git/' -e "ssh -i ~/.ssh/deploy_key -p $PORT" ./ $USERNAME@$HOST:/web/test/yeah-my-kanban
